CREATE TYPE "WorkShift" AS ENUM ('MORNING', 'AFTERNOON', 'NIGHT');

ALTER TABLE "Tenant"
ADD COLUMN "morningShiftStartMinutes" INTEGER NOT NULL DEFAULT 540,
ADD COLUMN "morningShiftEndMinutes" INTEGER NOT NULL DEFAULT 1080,
ADD COLUMN "afternoonShiftStartMinutes" INTEGER NOT NULL DEFAULT 780,
ADD COLUMN "afternoonShiftEndMinutes" INTEGER NOT NULL DEFAULT 1320,
ADD COLUMN "nightShiftStartMinutes" INTEGER NOT NULL DEFAULT 1320,
ADD COLUMN "nightShiftEndMinutes" INTEGER NOT NULL DEFAULT 360;

ALTER TABLE "EmployeeRegistrationRequest"
ADD COLUMN "workShift" "WorkShift" NOT NULL DEFAULT 'MORNING';

ALTER TABLE "Employee"
ADD COLUMN "workShift" "WorkShift" NOT NULL DEFAULT 'MORNING';

ALTER TABLE "Attendance"
ADD COLUMN "workShift" "WorkShift" NOT NULL DEFAULT 'MORNING';
